/*
 * Created on 19/giu/2010
 * Copyright (C) 2010 by Andrea Vacondio (andrea.vacondio@gmail.com).
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package org.sejda.core.support.io;

import java.io.File;

/**
 * Holds informations about an output file generated by a task. When fully populated holds a reference to the temporary file created by the task and information about the new name
 * for the temporary file.
 * 
 * @author Andrea Vacondio
 * 
 */
public final class FileOutput implements OnGoingFileOuputCreation, PopulatedFileOutput {

    private File file;
    private String name;

    private FileOutput(File file) {
        this.file = file;
    }

    /**
     * Entry point to populate the {@link FileOutput}
     * 
     * @param file
     * @return
     */
    public static OnGoingFileOuputCreation file(File file) {
        return new FileOutput(file);
    }

    public File getFile() {
        return file;
    }

    public String getName() {
        return name;
    }

    public PopulatedFileOutput name(String name) {
        this.name = name;
        return this;
    }
}
