/*
 * Created on 29/ago/2010
 *
 * Copyright 2010 by Andrea Vacondio (andrea.vacondio@gmail.com).
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License. 
 */
package org.sejda.core.support.io;

import static org.sejda.core.support.io.model.OutputDestination.destination;

import org.sejda.core.exception.TaskIOException;
import org.sejda.core.manipulation.model.output.AbstractPdfOutput;
import org.sejda.core.manipulation.model.output.OutputType;
import org.sejda.core.manipulation.model.output.PdfFileOutput;
import org.sejda.core.support.io.model.PopulatedFileOutput;

/**
 * Provides support methods for the tasks to handle write of output. When the task requires, it can flush to the output destination a single temporary file generated by the task
 * itself . An extending class can call the {@link SingleOutputSupport#flushSingleOutput(PopulatedFileOutput, AbstractPdfOutput, boolean)} to flush to the output destination.
 * 
 * <pre>
 * {@code
 * PopulatedFileOutput singleOut = file(tmpFile).name("newName");
 * AbstractPdfOutput output = ...
 * boolean overwrite = ...
 * flushSingleOutput(singleOut, output, overwrite);
 * }
 * </pre>
 * 
 * @author Andrea Vacondio
 * 
 */
public class SingleOutputWriterSupport extends OutputWriterSupport implements SingleOutputSupport {

    public void flushSingleOutput(PopulatedFileOutput fileOutput, AbstractPdfOutput output, boolean overwrite)
            throws TaskIOException {
        add(fileOutput);
        try {
            if (OutputType.FILE_OUTPUT.equals(output.getOutputType())) {
                write(destination((PdfFileOutput) output).overwriting(overwrite));
            } else {
                writeToNonFileDestination(output, overwrite);
            }
        } finally {
            clear();
        }
    }

}
