/*
 * Created on 19/giu/2010
 * Copyright (C) 2010 by Andrea Vacondio (andrea.vacondio@gmail.com).
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package org.sejda.core.support.io;

import java.io.File;

import org.sejda.core.support.io.handler.ToDestinationWriter.ToFileDestinationWriter;

/**
 * DSL interface to expose methods a single output task needs (tasks generating a single file as output).
 * 
 * @author Andrea Vacondio
 * 
 */
public interface SingleOutput {

    /**
     * Sets the temporary file generated by the task that will be written to the given destination.
     * 
     * @param file
     * @return the dsl interface exposing methods needed to set the destination.
     */
    ToFileDestinationWriter write(File file);

    /**
     * Sets the temporary file (and its name when it will be written) generated by the task that will be written to the given destination.
     * 
     * @param fileOutput
     * @return
     */
    ToFileDestinationWriter write(PopulatedFileOutput fileOutput);
}
