/*
 * Created on 29/ago/2010
 * Copyright (C) 2010 by Andrea Vacondio (andrea.vacondio@gmail.com).
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 */
package org.sejda.core.support.io;

import static org.sejda.core.support.io.model.OutputDestination.destination;

import org.sejda.core.exception.TaskIOException;
import org.sejda.core.manipulation.model.output.AbstractPdfOutput;
import org.sejda.core.manipulation.model.output.OutputType;
import org.sejda.core.manipulation.model.output.PdfFileOutput;
import org.sejda.core.support.io.model.PopulatedFileOutput;

/**
 * Provides support methods for the tasks to handle write of output. When the task requires, it can flush to the output destination a single temporary file generated by the task
 * itself . An extending class can call the {@link SingleOutputSupport#flushSingleOutput(PopulatedFileOutput, AbstractPdfOutput, boolean)} to flush to the output destination.
 * 
 * <pre>
 * {@code
 * PopulatedFileOutput singleOut = file(tmpFile).name("newName");
 * AbstractPdfOutput output = ...
 * boolean overwrite = ...
 * flushSingleOutput(singleOut, output, overwrite);
 * }
 * </pre>
 * 
 * @author Andrea Vacondio
 * 
 */
public class SingleOutputWriterSupport extends OutputWriterSupport implements SingleOutputSupport {

    public void flushSingleOutput(PopulatedFileOutput fileOutput, AbstractPdfOutput output, boolean overwrite)
            throws TaskIOException {
        add(fileOutput);
        try {
            if (OutputType.FILE_OUTPUT.equals(output.getOutputType())) {
                write(destination((PdfFileOutput) output).overwriting(overwrite));
            } else {
                writeToNonFileDestination(output, overwrite);
            }
        } finally {
            clear();
        }
    }

}
