name: build

on:
  push:
    branches: [ master, v6_experiments ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: ['25']
    runs-on: ${{ matrix.os }}
    name: JDK ${{ matrix.java }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up JDK
        uses: actions/setup-java@v5.2.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
